allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects { subproject ->
    subproject.pluginManager.withPlugin("com.android.library") {
        subproject.android {
            if (namespace == null) {
                def manifest = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
                if (manifest.exists()) {
                    def pkg = new XmlSlurper().parse(manifest).@package.text()
                    if (pkg) {
                        namespace = pkg
                    }
                }
            }
            compileSdkVersion 36
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_11
                targetCompatibility JavaVersion.VERSION_11
            }
            kotlinOptions {
                jvmTarget = '11'
            }
        }
    }
}

subprojects { subproject ->
    subproject.pluginManager.withPlugin("org.jetbrains.kotlin.android") {
        subproject.android {
            kotlinOptions {
                jvmTarget = '11'
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_11
                targetCompatibility JavaVersion.VERSION_11
            }
        }
    }
}

subprojects { subproject ->
    subproject.pluginManager.withPlugin("java-library") {
        subproject.java {
            sourceCompatibility = JavaVersion.VERSION_11
            targetCompatibility = JavaVersion.VERSION_11
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
