name: Main CI Build

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.8
          channel: stable
      - name: Decode keystore
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}

      - run: flutter pub get

      - name: Build Apks
        run: flutter build apk --release --split-per-abi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact - armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
          name: Miru-main-armeabi-v7a.apk

      - name: Upload Artifact - arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          name: Miru-main-arm64-v8a.apk

      - name: Upload Artifact - x86_64
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
          name: Miru-main-x86_64.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.8
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Rename directory
        run: |
          mv build/windows/x64/runner/Release build/windows/x64/runner/Miru-App

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: "build/windows/x64/runner/Miru-App"
          name: Miru-main-windows
